:numbered!:
["preface",sectnum="0"]

== Preface

=== Evaluation license

include::license-{license}.asciidoc[]

=== Foreword

Contexts and Dependency Injection 2.0 (link:https://jcp.org/en/jsr/detail?id=365[JSR-365^]) is an update to Contexts and Dependency Injection 1.2 (link:https://jcp.org/en/jsr/detail?id=346[JSR-346^]).

Starting with version 2.0 CDI targets Java SE and Java EE platforms.
CDI in java SE and CDI in a Java EE container share the features defined in core CDI.

[[doc_organisation]]

=== Organisation of this document

This document is organized in 4 parts:

* An introduction (this part), which is not part of the specification but introduce CDI concepts and give examples.
* The core CDI specification: <<part_1>>.
* Specific CDI features for Java SE: <<part_2>>.
* Specific CDI features for Java EE: <<part_3>>.


=== Major changes

This Early draft of CDI 2.0 includes important changes for the platform.

* The spec was split in 3 parts as desibed in <<doc_organisation>> to add the support for Java SE.
* API to boot CDI in Java SE, described in <<bootstrap-se>>
* Observer ordering, described in <<observer_ordering>>
* Asynchronous event, descibed in <<firing_events_asynchronously>>

The full changelog can be found link:https://issues.jboss.org/secure/ReleaseNote.jspa?version=12327364&styleName=Html&projectId=12311062[here^].

:numbered:
