[[selection_ee]]

=== Modularity in Java EE

[[declaring_selected_alternatives_application_ee]]

==== Declaring selected alternatives for an application in Java EE

When running in Java EE, the container must extend the rules defined for managed beans in <<declaring_selected_alternatives_application>> to EJB session beans.

[[declaring_selected_alternatives_bean_archive_ee]]

==== Declaring selected alternatives for a bean archive in Java EE

When running in Java EE, the container must extend the rules defined for managed beans in <<declaring_selected_alternatives_bean_archive>> to EJB session beans.


[[injection_ee]]

=== Dependency injection in Java EE

When running in Java EE, the container must extend the rules defined in <<injection>> and is also required to perform dependency injection whenever it creates one of the following objects:

* contextual instances of EJB session beans,
* non-contextual instances of EJB session beans (for example, session beans obtained by the application from JNDI or injected using +@EJB+), and
* instances of any other Java EE component class supporting injection.

A Java EE 5 container is not required to support injection for non-contextual objects.

[[instantiation_ee]]

==== Injection using the bean constructor in Java EE

When running in Java EE, the container must extend the rules defined for managed beans in <<instantiation>> to EJB session beans.

[[fields_initializer_methods_ee]]

==== Injection of fields and initializer methods in Java EE

When running in Java EE, the container must extend the rules defined for managed beans in <<fields_initializer_methods>> to EJB session beans.

