////
Copyright (c) 2015 Red Hat, Inc. and others

This program and the accompanying materials are made available under the
Apache Software License 2.0 which is available at:
https://www.apache.org/licenses/LICENSE-2.0.

SPDX-License-Identifier: Apache-2.0
////
[[type_level_inheritance_ee]]

=== Inheritance of type-level metadata in Jakarta EE

When running in Jakarta EE, the container must extend the rules defined for managed beans in <<type_level_inheritance>> to EJB session beans.



[[member_level_inheritance_ee]]

=== Inheritance of member-level metadata in Jakarta EE

When running in Jakarta EE, the container must extend the rules defined for managed beans in <<member_level_inheritance>> to EJB session beans.

[[specialization_ee]]

=== Specialization in Jakarta EE

[[direct_and_indirect_specialization_ee]]

==== Direct and indirect specialization in Jakarta EE

When running in Jakarta EE, the container must extend the rules defined in <<member_level_inheritance>> and is also required to support specialization for EJB session beans as defined in <<specialize_session_bean>>.
