source "https://rubygems.org"

gem 'asciidoctor'
# gem 'asciidoctor-diagram'
# gem 'tilt'
# gem 'slim'
gem 'thread_safe'
gem 'guard'
gem 'guard-shell'
gem 'guard-livereload'
gem 'rb-inotify'
gem 'yajl-ruby'
gem 'rb-readline'
