require 'erb'
require 'asciidoctor'
require 'asciidoctor/cli'

  guard :shell do
     watch (/^.+\.asciidoc$/) { |m| Asciidoctor::Cli::Invoker.new(%W(-o target/cdi-spec.html src/main/doc/cdi-spec.asciidoc)).invoke! }
  end

  guard 'livereload' do
    watch(%r{.+\.(css|js|html?|php|inc|theme)$})
  end
