:numbered!:
["preface",sectnum="0"]

== Preface

=== Evaluation license

....

Copyright 2009 Red Hat Middleware LLC.

All rights reserved.

NOTICE

The Specification is protected by copyright and the information described 
therein may be protected by one or more U.S. patents, foreign patents, or 
pending applications. Except as provided under the following license, no part of
the Specification may be reproduced in any form by any means without the prior 
written authorization of Red Hat Middleware LLC and its licensors, if any. Any 
use of the Specification and the information described therein will be governed
by the terms and conditions of this Agreement.

Subject to the terms and conditions of this license, including your compliance 
with Paragraphs 1 and 2 below, Red Hat Middleware LLC hereby grants you a 
fully-paid, non-exclusive, non-transferable, limited license (without the right 
to sublicense) under Red Hat Middleware LLC's intellectual property rights to:

1. Review the Specification for the purposes of evaluation. This includes: (i) 
developing implementations of the Specification for your internal, 
non-commercial use; (ii) discussing the Specification with any third party; and 
(iii) excerpting brief portions of the Specification in oral or written 
communications which discuss the Specification provided that such excerpts do 
not in the aggregate constitute a significant portion of the Specification.

2. Distribute implementations of the Specification to third parties for their 
testing and evaluation use, provided that any such implementation:

(i) does not modify, subset, superset or otherwise extend the Licensor Name 
Space, or include any public or protected packages, classes, Java interfaces, 
fields or methods within the Licensor Name Space other than those 
required/authorized by the Specification or Specifications being implemented;

(ii) is clearly and prominently marked with the word "UNTESTED" or "EARLY 
ACCESS" or "INCOMPATIBLE" or "UNSTABLE" or "BETA" in any list of available 
builds and in proximity to every link initiating its download, where the list or
link is under Licensee's control; and

(iii) includes the following notice:

"This is an implementation of an early-draft specification developed under the 
Java Community Process (JCP). The code is not compatible with any specification 
of the JCP."

The grant set forth above concerning your distribution of implementations of the
Specification is contingent upon your agreement to terminate development and 
distribution of your implementation of early draft upon final completion of the
Specification. If you fail to do so, the foregoing grant shall be considered 
null and void.

No provision of this Agreement shall be understood to restrict your ability to 
make and distribute to third parties applications written to the Specification.

Other than this limited license, you acquire no right, para or interest in or to
the Specification or any other Red Hat Middleware LLC intellectual property, 
and the Specification may only be used in accordance with the license terms set
forth herein. This license will expire on the earlier of: (a) two (2) years 
from the date of Release listed above; (b) the date on which the final version
of the Specification is publicly released; or (c) the date on which the Java 
Specification Request (JSR) to which the Specification corresponds is 
withdrawn. In addition, this license will terminate immediately without 
notice from Red Hat Middleware LLC if you fail to comply with any provision of 
this license. Upon termination, you must cease use of or destroy the 
Specification.

"Licensor Name Space" means the public class or interface declarations whose 
names begin with "java", "javax", "com.redhat" or their equivalents in any 
subsequent naming convention adopted through the Java Community Process, or any 
recognized successors or replacements thereof.

TRADEMARKS

No right, para, or interest in or to any trademarks, service marks, or trade 
names of Red Hat Middleware LLC or Red Hat's licensors is granted hereunder. 
Java and Java-related logos, marks and names are trademarks or registered 
trademarks of Sun Microsystems, Inc. in the U.S. and other countries.

DISCLAIMER OF WARRANTIES

THE SPECIFICATION IS PROVIDED "AS IS" AND IS EXPERIMENTAL AND MAY CONTAIN 
DEFECTS OR DEFICIENCIES WHICH CANNOT OR WILL NOT BE CORRECTED BY RED HAT 
MIDDLEWARE LLC. RED HAT MIDDLEWARE LLC MAKES NO REPRESENTATIONS OR WARRANTIES, 
EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT THAT THE 
CONTENTS OF THE SPECIFICATION ARE SUITABLE FOR ANY PURPOSE OR THAT ANY PRACTICE 
OR IMPLEMENTATION OF SUCH CONTENTS WILL NOT INFRINGE ANY THIRD PARTY PATENTS, 
COPYRIGHTS, TRADE SECRETS OR OTHER RIGHTS. This document does not represent any 
commitment to release or implement any portion of the Specification in any 
product.

THE SPECIFICATION COULD INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS. 
CHANGES ARE PERIODICALLY ADDED TO THE INFORMATION THEREIN; THESE CHANGES WILL BE 
INCORPORATED INTO NEW VERSIONS OF THE SPECIFICATION, IF ANY. RED HAT MIDDLEWARE 
LLC MAY MAKE IMPROVEMENTS AND/OR CHANGES TO THE PRODUCT(S) AND/OR THE PROGRAM(S) 
DESCRIBED IN THE SPECIFICATION AT ANY TIME. Any use of such changes in the 
Specification will be governed by the then-current license for the applicable 
version of the Specification.

LIMITATION OF LIABILITY

TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT WILL RED HAT MIDDLEWARE LLC OR 
ITS LICENSORS BE LIABLE FOR ANY DAMAGES, INCLUDING WITHOUT LIMITATION, LOST 
REVENUE, PROFITS OR DATA, OR FOR SPECIAL, INDIRECT, CONSEQUENTIAL, INCIDENTAL OR 
PUNITIVE DAMAGES, HOWEVER CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, 
ARISING OUT OF OR RELATED TO ANY FURNISHING, PRACTICING, MODIFYING OR ANY USE OF 
THE SPECIFICATION, EVEN IF RED HAT MIDDLEWARE LLC AND/OR ITS LICENSORS HAVE BEEN 
ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

You will hold Red Hat Middleware LLC (and its licensors) harmless from any 
claims based on your use of the Specification for any purposes other than the 
limited right of evaluation as described above, and from any claims that later 
versions or releases of any Specification furnished to you are incompatible with 
the Specification provided to you under this license.

RESTRICTED RIGHTS LEGEND

If this Software is being acquired by or on behalf of the U.S. Government or by 
a U.S. Government prime contractor or subcontractor (at any tier), then the 
Government's rights in the Software and accompanying documentation shall be only 
as set forth in this license; this is in accordance with 48 C.F.R. 227.7201 
through 227.7202-4 (for Department of Defense (DoD) acquisitions) and with 48 
C.F.R. 2.101 and 12.212 (for non-DoD acquisitions).

REPORT

You may wish to report any ambiguities, inconsistencies or inaccuracies you may 
find in connection with your evaluation of the Specification ("Feedback"). To 
the extent that you provide Red Hat Middleware LLC with any Feedback, you 
hereby: (i) agree that such Feedback is provided on a non-proprietary and 
non-confidential basis, and (ii) grant Red Hat Middleware LLC a perpetual, 
non-exclusive, worldwide, fully paid-up, irrevocable license, with the right to 
sublicense through multiple levels of sublicensees, to incorporate, disclose, 
and use without limitation the Feedback for any purpose related to the 
Specification and future versions, implementations, and test suites thereof.

GENERAL TERMS

Any action related to this Agreement will be governed by California law and 
controlling U.S. federal law. The U.N. Convention for the International Sale of 
Goods and the choice of law rules of any jurisdiction will not apply.

The Specification is subject to U.S. export control laws and may be subject to 
export or import regulations in other countries. Licensee agrees to comply 
strictly with all such laws and regulations and acknowledges that it has the 
responsibility to obtain such licenses to export, re-export or import as may be 
required after delivery to Licensee.

This Agreement is the parties' entire agreement relating to its subject matter. 
It supersedes all prior or contemporaneous oral or written communications, 
proposals, conditions, representations and warranties and prevails over any 
conflicting or additional terms of any quote, order, acknowledgment, or other 
communication between the parties relating to its subject matter during the term 
of this Agreement. No modification to this Agreement will be binding, unless in 
writing and signed by an authorized representative of each party.

....

=== Foreword

Contexts and Dependency Injection 1.1 (JSR-346) is an update to Contexts and Dependency Injection 1.0 (JSR-299). A full changelog can be found in the issue tracker link:$$https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12311062&version=12315956$$[release notes for CDI 1.1].

=== Major changes

==== 1.1 Early Draft Review

* +@Disposes+  methods for producer fields
* The +CDI+ class, which provides programmatic access to CDI facilities from outside a managed bean
* Pass the qualifiers an event was fired with to the +ObserverMethod+
* Ability to veto beans declaratively using +@Vetoed+
* Conversations in Servlet requests* Application lifecycle events in Java EE
* Injection of +Bean+  metadata into bean instances
* Programmatic access to a container provided +Producer+, +InjectionTarget+, +AnnotatedType+
* Ability to override attributes of a +Bean+  via +BeanAttributes+
* Ability to process modules via +ProcessModule+
* Ability to wrap the +InjectionPoint+
* Ability to obtain +Extension+  instances from +BeanManager+
* Injection of the +ServletContext+
* Access to +beans.xml+  in +ProcessModule+

==== 1.1 Public Review Draft

* +ProcessAnnotatedType+  fired for annotations
* Moved all Bean Validation integration to Bean Validation Specification as Bean Validation 1.1 Public Review Draft
* Clarify what beans are available during container lifecycle events
* Honor +WEB-INF/classes/META-INF/beans.xml+  to activate +WEB-INF/classes+  a bean archive
* Global ordering and enablement of interceptors and decorators
* Global selection of alternatives
* @New deprecated
* JMS +MessageListener+  removed as not available in Java EE
* Support for unmanaged instances via +Instance.destroy()+
* Clarify interceptors and decorators must be implemented using proxying
* Allow multiple annotated types per Java class
* Allow Extensions to specify the annotations that they are interested in

=== Open issues

The expert group still has a number of topics under discussion, as of the Public Review Draft. Some of these are minor, alignment issues, or naming issues, however some of these directly affect core CDI concepts, and these are listed here.

==== Bean visibility

The CDI 1.0 specification clearly states that _only_ beans whose bean class is accessible (using standard classloader visibility rules) can be injected into another bean. For example, if you have a bean A in WAR, assuming standard Java EE classloader structure, it wouldn't be available for injection in bean B, in an EJB module. This generally makes sense, as the type is not visible either.

CDI also offers two options to replace bean implementations transparently, without explicitly selecting that implementation (either by type or using a qualifier) - alternatives and specialization. In this case, it is less clear that the bean class of the specializing bean, or the bean class selected alternative, must be visible.

The CDI EG is still debating this issue, including whether to offer a backwards incompatible mode here.

==== +@ApplicationScoped+ beans shared between all EAR modules

CDI implementations have not consistently shared +@ApplicationScoped+ beans across all modules of an EAR. This issue heavily relates to _Bean visibility_. The CDI 1.1 specification will clearly state how +@ApplicationScoped+ are shared.

==== Startup event

A commonly requested feature is for the application to be able to do some work once the application has started but before it starts servicing requests originating remotely. Currently CDI 1.1 defines a +@Initialized(ApplicationScoped.class)+ which is called when the application context starts, but we are investigating whether this can be extended to provide a more general startup event.

If we define such an event, we need to allow custom contexts to activate themselves whilst it is executing, however this is likely beyond the scope of CDI 1.1 and will likely be addressed in CDI 2.0.

==== +@WithAnnotations+

CDI 1.1 adds +@WithAnnotations+ which allows an extension observing +ProcessAnnotatedType+ to filter which types it sees. We would like to provide such functionality for all container lifecycle event observers, but there are some interesting things to consider, including whether it would be better to filter on qualifiers for later events. CDI 1.1 may or may not add such support, and we are looking for feedback on this.

==== Allowing arrays as qualifier members

CDI 1.0 requires array valued members of qualifiers to be annotated with +@Nonbinding+, excluding them from the resolution process. The JDK defines that annotation equality for array valued members should use +Arrays.equals()+, which requires two identical arrays (equal values, in the same order) in order to return true.

We feel that to make array valued members of qualifiers useful, we need to offer a pluggable strategy for checking equality of arrays, as often it would be desirable to consider two arrays with the same values, in any order, as equal. We intend to add this for CDI 1.1.

==== Restricting what CDI scans

CDI 1.0 will scan all classes in a jar with +beans.xml+. We plan to add a syntax to +beans.xml+ that will the application developer to exclude classes using a variety of filtering options (e.g. by package). Weld offers such a syntax, and will be used as a starting point for CDI link:$$http://docs.jboss.org/weld/reference/1.1.5.Final/en-US/html/configure.html#d0e5769$$[].

==== Observer resolution

CDI 1.0 requires the type used for observer resolution to be based on the runtime type of the event object. Unfortunately, the JDK erases generic type information about objects that we need to allow firing of many events with parameterized types. CDI 1.0 also completely ignores the generic type of the injected event object, which does typically contain the needed type information. We therefore intend to change the event observer resolution rules to allow the generic type of the event object to be taken into account if the runtime event object does not contain sufficient information.

Note that this may seem like a backwards incompatible change, however CDI 1.0 is essentially unimplementable today - examples in the spec do not work as described.

:numbered:

