= CDI Specification document generation

This module contains AsciiDoc sources and configuration to generate CDI documentation in HTML and PDF format for both Apache License 2 and Jakarta Eclipse Foundation Specification Process.

== Generating the documentation

Just enter `mvn` at the command line.
Maven will generate final doc in HTML and PDF in `target` directory with the default license (ASL2).

== License in doc

The documentation can be generated for 2 licenses : Apache License v 2.0 (by default) and EFSL license.
To generate doc with the final EFSL license, change the `license-file` property to `final`. Use `asl` or
specify nothing for the Apache V2 License.

For instance `mvn -Dlicense-file=final` will generate docs with link:https://www.eclipse.org/legal/efsl.php[EFSL] final license.

== Working on the spec

The spec is split different AsciiDoc file in `src/main/asciidoc`
The master doc (entry point) is `cdi-spec.asciidoc` which includes all the other part of the spec.

To work in the spec you may want to install a plugin in your IDE (major 3 IDE have AsciiDoc plugins).
You can also use a good text editor providing AsciiDoc plugin.
Best candidate are:

=== Atom

Install https://atom.io/[Atom].
Then from the Atom editor menus, navigate to menu:Atom[Preferences].
From there, open the menu:Packages[] tab and install:

AsciiDoc Preview package:: enables live preview
AsciiDoc package:: enables syntax highlighting (AsciiDoc language support)

More information:

* https://atom.io/packages/asciidoc-preview[AsciiDoc Preview for Atom]
* https://atom.io/packages/language-asciidoc[AsciiDoc language support for Atom]

=== Brackets

Install http://brackets.io/[Brackets].
Then from the Brackets file menu, open the extension manager.
Browse available extensions and install `AsciiDoc Preview`.

More information:

* https://github.com/asciidoctor/brackets-asciidoc-preview[AsciiDoc Preview for Brackets]

=== AsciiDocFX

To run AsciiDocFX, you will need to:

. Install http://www.oracle.com/technetwork/java/javase/downloads/index.html[JDK 8]
. Download the latest https://github.com/rahmanusta/AsciidocFX/releases[AsciidocFX.zip] and extract it
. Run `bin/asciidocfx.bat` or `bin/asciidocfx.sh`

More information:

 * http://www.asciidocfx.com/[AsciiDocFX homepage]

