[[se_bootstrap]]

== Bootstrapping a CDI container in Java SE

In Java SE, the CDI container must be explicitly bootstrapped by the user.
This is performed with the `SeContainerInitializer` abstract class and its static method `newInstance()`.

`SeContainerInitializer` implementation is obtained by java service-provider.
It allows the configuration of the CDI container before its bootstrapping.
Calling the `initialize()` method bootstraps the container and return a `SeContainer`.

User can shutdown the container manually by calling the `close()` method on `SeContainer` or automatically since `SeContainer` implements `AutoCloseable` interface.

[[se_container_initializer]]

=== `SeContainerInitializer` class

CDI Container can be configured and bootstrapped from `javax.enterprise.inject.se.SeContainerInitializer` abstract class.

A CDI implementation is required to provide an implementation of `SeContainerInitializer` declared as a service-provider.
`newInstance()` static method uses java service-provider to obtain an implementation of `SeContainerInitializer` and return an instance of it.
There must be exactly one provider available, otherwise an IllegalStateException is thrown.

`SeContainerInitializer` configuration allows explicit addition of elements to the set of automatically discovered elements.
These additions are done in an internal synthetic bean archive that is added to the set of bean archives discovered by the container during deployment.

This synthetic bean archive behaves like an explicit bean archive (as defined in <<bean_archive>>).

[source, java]
----
public abstract class SeContainerInitializer {
    public static SeContainerInitializer newInstance() { ... }
    public SeContainerInitializer addBeanClasses(Class<?>... classes);
    public SeContainerInitializer addPackages(Class<?>... packageClasses);
    public SeContainerInitializer addPackages(boolean scanRecursively, Class<?>... packageClasses);
    public SeContainerInitializer addPackages(Package... packages);
    public SeContainerInitializer addPackages(boolean scanRecursively, Package... packages);
    public SeContainerInitializer addAnnotatedTypes(AnnotatedType<?>... annotatedTypes);
    public SeContainerInitializer addExtensions(Extension... extensions);
    public SeContainerInitializer addExtensions(Class<? extends Extension>... extensions);
    public SeContainerInitializer addInterceptors(Class<?>... interceptorClasses);
    public SeContainerInitializer addDecorators(Class<?>... decoratorClasses);
    public SeContainerInitializer addAlternatives(Class<?>... alternativeClasses);
    public SeContainerInitializer addAlternativeStereotypes(Class<? extends Annotation>... alternativeStereotypeClasses);
    public SeContainerInitializer addProperty(String key, Object value);
    public SeContainerInitializer setProperties(Map<String, Object> properties);
    public SeContainerInitializer addBeans(Bean<?>... beans);
    public SeContainerInitializer disableDiscovery();
    public SeContainerInitializer setClassLoader(ClassLoader classLoader);
    public SeContainer initialize();
}
----

Unless specified differently each methods of `SeContainerInitializer` returns the current `SeContainerInitializer` object.

* `newInstance()` static method returns an instance of the implementation of `SeContainerInitializer` discovered by java service-provider.
Each call returns a new instance of `SeContainerInitializer`.
* `addBeanClasses()` add classes to the the synthetic bean archive
* `addPackages()` add packages content to the synthetic bean archive.
Versions exist by providing classes in the wished package or `Package` objects themselves.
Other version of the method allows recursive addition
* `addAnnotatedTypes()` add the provided `AnnotatedTypes` to the synthetic bean archive.
* `addExtensions()` add the provided extensions (class or instance) to the synthetic bean archive.
* `addInterceptors()` add the provided interceptors to the synthetic bean archive.
* `addDecorators()` add the provided decorators to the synthetic bean archive.
* `addAlternatives()` add the provided alternatives classes to the synthetic bean archive.
* `addAlternativeStereotypes()` add the provided stereotypes classes to the synthetic bean archive.
* `addProperty()` add a configuration property for the container
* `SetProperties()` set the Map of configuration properties for the container.
replace previous properties.
* `addBeans()` add the provided beans to the set of discovered beans.
* `disableDiscovery()` deactivate automatic type scanning and discovery.
All bean archive will be ignored except the implicit bean archive.
* `setClassLoader()` change the default class loader for the container
* `initialize()` bootstrap the container and returns a `SeContainer` object as defined in <<se_container>>.



Each time `initialize()` method is called on the `SeContainerInitializer` it returns a new `SeContainer<Object>` instance.
The _application context_ is started automatically by the container on start up.
An implementation need not support calling `initialize()` multiple times on `SeContainerInitializer` without the previously returned `SeContainer` being shutdown.


[[se_container]]

=== `SeContainer` class

The `javax.enterprise.inject.se.SeContainer` inherits the `javax.enterprise.inject.spi.CDI` class as defined in <<provider>>.


[source, java]
----
public abstract class SeContainer extends CDI<Object> implements AutoCloseable {
    public abstract void close();
    public abstract boolean isRunning();
}
----


`SeContainer` implements `AutoCloseable`, so when dereferenced it should shutdown automatically.

The `SeContainer` instance may also be stopped manually by explicitly calling the `close()` method on the `SeContainer` object.
 If the `close()` method is explicitly invoked and the container was already stopped, an `IllegalStateException` will be thrown.

State of the container can be checked with `isRunning()` method which returns `true` if called before container shutdown and `false` after.

The following code example are equivalent:

[source,java]
----
public static void main(String... args) {
    SeContainerInitializer containerInit = SeContainerInitializer.newInstance();
    SeContainer container = containerInit.initialize();
    // retrieve a bean and do work with it
    MyBean myBean = container.select(MyBean.class).get();
    myBean.doWork();
    // when done
    container.close();
}
----


[source,java]
----
public static void main(String... args) {
    try(SeContainer container = SeContainerInitializer.newInstance().initialize()) {
        // start the container, retrieve a bean and do work with it
        MyBean myBean = container.select(MyBean.class).get();
        myBean.doWork();
    }
    // shuts down automatically after the try with resources block.
}
----

