[[se_bootstrap]]

== Bootstrapping a CDI container in Java SE

In Java SE, the CDI container must be explicitly bootstrapped by the user.
This is performed with the `SeContainerInitializer` abstract class and its static method `newInstance()`.

`SeContainerInitializer` is a service provider of the service `javax.enterprise.inject.se.SeContainerInitializer` declared in META-INF/services.
It allows the configuration of the CDI container before its bootstrapping.
The `SeContainerInitializer.initialize()` method bootstraps the container and returns a `SeContainer` instance.

User can shutdown the container manually by calling the `close()` method on `SeContainer` or automatically since `SeContainer` extends `AutoCloseable` interface.

[[se_container_initializer]]

=== `SeContainerInitializer` class

CDI Container can be configured and bootstrapped from `javax.enterprise.inject.se.SeContainerInitializer` abstract class.

A CDI implementation is required to provide an implementation of `SeContainerInitializer` declared as a service-provider.
`newInstance()` static method uses java service-provider to obtain an implementation of `SeContainerInitializer` and return an instance of it.
There must be exactly one provider available, otherwise an IllegalStateException is thrown.

`SeContainerInitializer` configuration allows explicit addition of elements to the set of automatically discovered elements.
These additions are done in an internal synthetic bean archive that is added to the set of bean archives discovered by the container during deployment.

This synthetic bean archive behaves like an explicit bean archive (as defined in <<bean_archive>>).

[source, java]
----
public abstract class SeContainerInitializer {
    public static SeContainerInitializer newInstance() { ... }
    public SeContainerInitializer addBeanClasses(Class<?>... classes);
    public SeContainerInitializer addPackages(Class<?>... packageClasses);
    public SeContainerInitializer addPackages(boolean scanRecursively, Class<?>... packageClasses);
    public SeContainerInitializer addPackages(Package... packages);
    public SeContainerInitializer addPackages(boolean scanRecursively, Package... packages);
    public SeContainerInitializer addExtensions(Extension... extensions);
    public SeContainerInitializer addExtensions(Class<? extends Extension>... extensions);
    public SeContainerInitializer addInterceptors(Class<?>... interceptorClasses);
    public SeContainerInitializer addDecorators(Class<?>... decoratorClasses);
    public SeContainerInitializer addAlternatives(Class<?>... alternativeClasses);
    public SeContainerInitializer addAlternativeStereotypes(Class<? extends Annotation>... alternativeStereotypeClasses);
    public SeContainerInitializer addProperty(String key, Object value);
    public SeContainerInitializer setProperties(Map<String, Object> properties);
    public SeContainerInitializer disableDiscovery();
    public SeContainerInitializer setClassLoader(ClassLoader classLoader);
    public SeContainer initialize();
}
----

Unless specified differently each method of `SeContainerInitializer` returns the current `SeContainerInitializer` object.

* `newInstance()` static method returns an instance of the implementation of `SeContainerInitializer` discovered by java service-provider.
Each call returns a new instance of `SeContainerInitializer`.
* `addBeanClasses()` add classes to the the synthetic bean archive
* `addPackages()` add packages content to the synthetic bean archive.
Versions exist by providing classes in the wished package or `Package` objects themselves.
Other version of the method allows recursive addition
* `addExtensions()` add the provided extensions (class or instance) to the synthetic bean archive.
* `addInterceptors()` add the provided interceptors to the synthetic bean archive.
* `addDecorators()` add the provided decorators to the synthetic bean archive.
* `addAlternatives()` add the provided alternatives classes to the synthetic bean archive.
* `addAlternativeStereotypes()` add the provided stereotypes classes to the synthetic bean archive.
* `addProperty()` add a configuration property for the container
* `SetProperties()` set the Map of configuration properties for the container.
replace previous properties.
* `disableDiscovery()` deactivate automatic type scanning and discovery.
All bean archive will be ignored except the implicit bean archive.
* `setClassLoader()` change the default class loader for the container
* `initialize()` bootstrap the container and returns a `SeContainer` as defined in <<se_container>>.



Every invocation of the `SeContainerInitializer.initialize()` method returns a new `SeContainer instance.
The _application context_ is started automatically by the container on start up.
An implementation need not support calling `initialize()` multiple times on `SeContainerInitializer` without the previously returned `SeContainer` being shutdown.


[[se_container]]

=== `SeContainer` interface


The `javax.enterprise.inject.se.SeContainer` interface provides access to the `BeanManager` and programmatic lookup as defined in <<dynamic_lookup>>.
`SeContainer` also extends `AutoCloseable`, so when dereferenced, it should shutdown automatically.


[source, java]
----
public interface SeContainer extends Instance<Object>,AutoCloseable {
    void close();
    boolean isRunning();
    BeanManager getBeanManager();
}
----


* `close()` method explicitly shutdown the container.
If it is called and the container was already shutdown, it throws an `IllegalStateException`.
* `isRunning()` method returns `true` if called before container shutdown and `false` after.
* `getBeanManager()` method returns the `BeanManager` (as defined in <<beanmanager>>) for the running container.
if it is called and the container was already shutdown, it throws an `IllegalStateException`.

The following code example are equivalent:

[source,java]
----
public static void main(String... args) {
    SeContainerInitializer containerInit = SeContainerInitializer.newInstance();
    SeContainer container = containerInit.initialize();
    // retrieve a bean and do work with it
    MyBean myBean = container.select(MyBean.class).get();
    myBean.doWork();
    // when done
    container.close();
}
----


[source,java]
----
public static void main(String... args) {
    try(SeContainer container = SeContainerInitializer.newInstance().initialize()) {
        // start the container, retrieve a bean and do work with it
        MyBean myBean = container.select(MyBean.class).get();
        myBean.doWork();
    }
    // shuts down automatically after the try with resources block.
}
----

